# Generated by Django 5.2 on 2025-05-04 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('download_type', models.CharField(choices=[('PNG', 'PNG'), ('SVG', 'SVG'), ('DXF', 'DXF')], max_length=10)),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
