# Generated by Django 5.2 on 2025-05-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadRecord',
        ),
    ]
